services:

  jaeger:
    image: jaegertracing/all-in-one:1.49
    ports:
      - "16686:16686"

  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/local-config.yaml

  otelcol:
    image: otel/opentelemetry-collector
    restart: always
    ports:
      - 4317:4317
    volumes:
      - ./otelcol.yml:/etc/otelcol/config.yaml

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.4.1
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    depends_on:
      - loki